version: '3'

services:
  proxy:
    build:
      context: ./nginx
    volumes:
      - ./api:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php
    links:
      - php
    ports:
      - "80:80"
      - "443:443"

  php:
    build:
      context: ./api
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN}
      - TRUSTED_HOSTS=${TRUSTED_HOSTS}
    volumes:
      - ./api:/var/www

  web:
    build:
      context: ./web
    command: sh -c "npm start"
    depends_on:
      - php
    volumes:
      - ./web:/home/node/app
      - node_modules:/home/node/app/node_modules

  db:
    image: postgres:12
    restart: always
    environment:
        POSTGRES_PASSWORD: password
        POSTGRES_DB: yourbudget
    ports:
        - 5432:5432

volumes:
  node_modules:
